version: 2.1

jobs:
  generate:
    parallelism: 2
    resource_class: small
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Generate foo.txt
          command: |
            curl -s https://ramenipsum.herokuapp.com/paragraphs/1 > foo.txt
            cat foo.txt
      - store_artifacts:
          path: README.md
      - store_artifacts:
          path: ramenipsum.txt
      - store_artifacts:
          path: foo.txt
      - run:
          name: Print artifact URLs
          environment:
            CIRCLE_ARTIFACT_DOMAIN: output.circle-artifacts.com 
          command: |
            echo "https://${CIRCLE_ARTIFACT_DOMAIN}/output/job/${CIRCLE_WORKFLOW_JOB_ID}/artifacts/${CIRCLE_NODE_INDEX}/README.md"
            echo "https://${CIRCLE_ARTIFACT_DOMAIN}/output/job/${CIRCLE_WORKFLOW_JOB_ID}/artifacts/${CIRCLE_NODE_INDEX}/ramenipsum.txt"
            echo "https://${CIRCLE_ARTIFACT_DOMAIN}/output/job/${CIRCLE_WORKFLOW_JOB_ID}/artifacts/${CIRCLE_NODE_INDEX}/foo.txt"

workflows:
  artifacts-are-fun:
    jobs:
      - generate
